CreateOrder:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./CreateOrder
      Handler: com.fbp.CreateOrderLambda::createOrder
      Runtime: java17
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:  # Moved inside Properties
        Variables:
          FBP_USERS_TABLE_NAME: FBPUsers  # Use existing table name directly
      Policies:  # Moved inside Properties
        - DynamoDBCrudPolicy:
          TableName: FBPUsers  # Use existing table name directly
      Events:
        CreateOrder:
          Type: Api
          Properties:
            Path: /createOrder
            Method: POST
            # Removed RestApiId - let SAM auto-create the API
